version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "go-crud-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r6g1jivl0z8z"
s3_prefix = "go-crud-api"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
