AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: scirone-go-break-memory
      Handler: main
      Runtime: go1.x
      Tags:
        Author: S.Cirone
